[package]
name = "wol"
version = "0.1.0"
authors = ["蔡斌卿 <caibinqing@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
eui48 = "0.4"

[dev-dependencies]
rand = "0.7"
